apiVersion: v2
name: kube-downscaler
description: A Helm chart for kube-downscaler
home: https://github.com/hjacobs/kube-downscaler

type: application

version: 0.1.0

appVersion: 20.4.3

dependencies:
  - name: common
    version: 0.3.0
    repository: https://hahow-helm-charts.storage.googleapis.com/
